name: build

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - run: make
        env:
          GOOS: linux
          GOARCH: amd64

      - uses: actions/upload-artifact@v3
        with:
          name: oci-add-hooks
          path: oci-add-hooks